<?php

namespace App\Filament\Resources\CommonCategoryResource\Pages;

use App\Filament\Resources\CommonCategoryResource;
use Filament\Pages\Actions;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Database\Eloquent\Model;

class EditCommonCategory extends EditRecord
{
    protected static string $resource = CommonCategoryResource::class;


    protected function mutateFormDataBeforeFill(array $data): array
    {
        $translations = [];
        foreach ($this->record->translations as $item){
            $translations[$item->lang] = [
                'name' => $item->name,
            ];
        }
        $data['translations'] = $translations;
        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }

    protected function handleRecordUpdate(Model $record, array $data): Model
    {

        $record->update($data);

        $record->translations()->delete();
        foreach ($data['translations'] as $lang => $item){
            $record->translations()->create([
                'lang' => $lang,
                'name' => $item['name'],
            ]);

        }

        return $record;
    }

    protected function getActions(): array
    {
        return [
            Actions\ViewAction::make(),
            Actions\DeleteAction::make(),
        ];
    }
}
