<?php

namespace App\Filament\Resources\CategoryResource\Pages;

use App\Filament\Resources\CategoryResource;
use App\Models\CommonCategory;
use App\Models\Restaurant;
use Filament\Forms\Components\Hidden;
use Filament\Forms\Components\MarkdownEditor;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Tabs;
use Filament\Forms\Components\Tabs\Tab;
use Filament\Forms\Components\TextInput;
use Filament\Pages\Actions;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Database\Eloquent\Model;

class EditCategory extends EditRecord
{
    protected static string $resource = CategoryResource::class;


    protected function mutateFormDataBeforeFill(array $data): array
    {
        $translations = [];
        foreach ($this->record->translations as $item){
            $translations[$item->lang] = [
                'name' => $item->name,
                'description' => $item->description,
            ];
        }
        $data['translations'] = $translations;
        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }

    protected function handleRecordUpdate(Model $record, array $data): Model
    {

        $record->update($data);

        $record->translations()->delete();
        foreach ($data['translations'] as $lang => $item){
            $record->translations()->create([
                'lang' => $lang,
                'name' => $item['name'],
                'description' => $item['description'],
            ]);

        }

        return $record;
    }

    protected function getActions(): array
    {
        return [
            Actions\ViewAction::make(),
            Actions\DeleteAction::make(),
        ];
    }
}
